Repository codetapacademy/all-on-red-with-react, pull requests merged in 2020-02, with the labels that each got.

#1 test
  src/App.js
Labels: good first issue

#8 feat: [psyhedeliq] create number slot component
  src/component/circle/circle.component.jsx
  src/component/circle/circle.style.js
  src/component/number-slot/index.js
  src/component/number-slot/number-slot.component.jsx
  src/component/number-slot/number-slot.style.js
Labels: enhancement, good first issue

#15 feat: [psyhedeliq] create sphere component
  src/component/circle/circle.component.jsx
  src/component/circle/circle.style.js
  src/component/sphere/index.js
  src/component/sphere/sphere.component.jsx
  src/component/sphere/sphere.style.js
Labels: enhancement, good first issue

#39 start working on my roulette app
  package.json
  public/index.html
  src/component/app/app.component.jsx
  src/component/app/index.js
  src/component/board/board.component.jsx
  src/component/board/board.style.js
  src/component/board/index.js
  src/component/slot/index.js
  src/component/slot/slot.component.jsx
  src/component/slot/slot.style.js
  src/index.jsx
Labels: enhancement

#24 feat: [psyhedeliq] generate a collection of possible elections
  src/component/circle/circle.component.jsx
  src/component/elected/elected.component.jsx
  src/component/elected/elected.style.js
  src/component/elected/index.js
Labels: enhancement, good first issue

#46 create a collection of objects with number rotation and color
  src/component/board/board.component.jsx
  src/component/board/board.style.js
  src/component/slot/slot.component.jsx
  src/component/slot/slot.style.js
Labels: enhancement

#38 feat: [bogdanNegura] - start the roulette with the basic setUp
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  src/component/app/app.component.jsx
  src/component/app/app.style.js
  src/component/app/index.js
  src/component/bord/board.component.jsx
  src/component/bord/board.style.js
  src/component/bord/index.js
  src/component/slot/index.js
  src/component/slot/slot.component.jsx
  src/component/slot/slot.style.js
  src/index.jsx
Labels: documentation, enhancement

#50 start working on ball
  src/component/ball/ball.component.jsx
  src/component/ball/ball.style.js
  src/component/ball/index.js
  src/component/board/board.component.jsx
  src/component/board/board.style.js
  src/component/selected/index.js
  src/component/selected/selected.component.jsx
  src/component/selected/selected.style.js
Labels: enhancement
